export const PAGE_ACTION = {
  REQUEST_PARTICIPANTS_LIST: 'PAGE_ACTION_REQUEST_PARTICIPANTS_LIST',
  ACTIVATE_PICTURE_IN_PICTURE: 'PAGE_ACTION_ACTIVATE_PICTURE_IN_PICTURE',
};

export const CONTENT_SCRIPT = {
  INITIALIZE: 'CONTENT_SCRIPT_INITIALIZE',
  REQUEST_PARTICIPANTS_LIST: 'CONTENT_SCRIPT_REQUEST_PARTICIPANTS_LIST',
  ACTIVATE_PICTURE_IN_PICTURE: 'CONTENT_SCRIPT_ACTIVATE_PICTURE_IN_PICTURE',
};

export const STATUS = {
  SUCCESS: 'STATUS_SUCCESS',
  FAIL: 'STATUS_FAIL',
};

export const ERROR = {
  UNKNOWN_TYPE: 'ERROR_UNKNOWN_TYPE',
  NO_ACTIVE_TAB: 'ERROR_NO_ACTIVE_TAB',
  NOT_IN_MEETING: 'ERROR_NOT_IN_MEETING',
  OPERATION_FAILED: 'ERROR_OPERATION_FAILED',
};
