export const PAGE_ACTION = {
  REQUEST_PARTICIPANTS_LIST: 'PAGE_ACTION_REQUEST_PARTICIPANTS_LIST',
};

export const CONTENT_SCRIPT = {
  INITIALIZE: 'CONTENT_SCRIPT_INITIALIZE',
  REQUEST_PARTICIPANTS_LIST: 'CONTENT_SCRIPT_REQUEST_PARTICIPANTS_LIST',
};

export const STATUS_SUCCESS = 'SUCCESS';
export const STATUS_FAILED = 'FAILED';
export const ERROR_UNKNOWN_TYPE = 'ERROR_UNKNOWN_TYPE';
export const ERROR_NO_ACTIVE_TAB = 'ERROR_NO_ACTIVE_TAB';
export const ERROR_NOT_IN_MEETING = 'ERROR_NOT_IN_MEETING';
